import type { Metadata } from "next";
import localFont from "next/font/local";
import 'csh-material-bootstrap/dist/csh-material-bootstrap.css'
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "ak's CSH React Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
